### ISSUE TITLE
images are missing

### ISSUE THREAD

**Issue by macmarrum** [nnako/freeplane-packer#1]
The packed mmx.zip contains a linked mm file but is missing a linked image

```log
---- PACKING FREEPLANE CONTAINER
root - DEBUG    - mindmap "/home/m/freeplane/test-mmx-packer.mm" will be exported into a container
root - INFO     - file "/home/m/tmp/test-mmx-packer-target-1.mm" was found
```
[test-mmx-packer.mmx.zip](https://github.com/nnako/freeplane-packer/files/10215682/test-mmx-packer.mmx.zip)

**Comment by nnako** [comment]
Hi @macmarrum . thanks for your reply :-) .

I will have to update the framework code to v0.2 as well as the freeplane-python-ui library to v0.7, soon. currently, in-line images are represented within "hooks" of respective XML elements. but up to now, these are not evaluated in my libraries...

Thanks.

**Comment by nnako** [comment]
please install / update to **v0.7.0** of the [freeplane-python-io](https://pypi.org/project/freeplane-io/) package and try the latest freeplane-packer. It should work now.

**Comment by macmarrum** [comment]
thanks
it works
