### ISSUE TITLE
html img is missed

### ISSUE THREAD

**Issue by macmarrum** [nnako/freeplane-packer#3]
Local html img is missed.

Example from `freeplaneFunctions.mm`
```xml
<node ID="ID_300419503" CREATED="1319798221748" MODIFIED="1620564016975" STYLE="bubble"><richcontent TYPE="NODE">

<html>
  <head>
    
  </head>
  <body>
    <img src="Images/doc/freeplaneApplications.png"/>
  </body>
</html>
</richcontent>
```

1. Open Freeplane
2. `Help->Tutorial`
3. `Tools->Open current map directory`
4. Copy the path to the file `freeplaneFunctions.mm`
5. Work around #2 by replacing `&nbsp;`, e.g. `$ python -c "import sys; from pathlib import Path; enc='U8'; p1 = Path(sys.argv[1]); p2 = Path(sys.argv[2]) if len(sys.argv) >= 3 else p1.with_name(f'{p1.stem}-no_nbsp{p1.suffix}'); text = p1.read_text(encoding=enc).replace('&nbsp;', ' '); p2.write_text(text, encoding=enc)" <path-to-the-file> [<path-to-the-cleaned-up-file>]`
6. Pack the file: `$ python packer.py pack <path-to-the-cleaned-up-file>`

```bash
$ python packer.py pack /home/data/git-repos/freeplane-macmarrum/BIN/doc/freeplaneFunctions-no_nbsp.mm --mmxpath ~/tmp/x.mmx
root - INFO     - file "/home/data/git-repos/freeplane-macmarrum/BIN/doc/latestFreeplaneFeatures.mm" was found
```

The resulting mmx (zip) is missing `freeplaneApplications.png`

**Comment by nnako** [comment]
thanks for your reply.

from **v0.3** paths given within HTML node content are integrated into the container and linked accordingly.

please update locally and check. thanks.
